<!--
 * Created by PhpStorm.
 * User: whiteco
 * Date: 4/15/2015
 * Time: 8:06 PM
 */

//including this file on the bottom of each file so we can easily update the versions if necessary
-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>

<!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/dt/dt-1.10.9/datatables.min.css"/> -->
<!--<script type="text/javascript" src="https://cdn.datatables.net/r/dt/dt-1.10.9/datatables.min.js"></script> -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/dt-1.10.9/jqc-1.11.3,dt-1.10.9,b-1.0.3,se-1.0.1/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="Editor-1.5.1/css/editor.dataTables.css">



<script type="text/javascript" src="https://cdn.datatables.net/r/dt-1.10.9/jqc-1.11.3,dt-1.10.9,b-1.0.3,se-1.0.1/datatables.min.js"></script>
<script type="application/javascript" src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="Editor-1.5.1/js/dataTables.editor.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>