<!--
 * Created by PhpStorm.
 * User: whiteco
 * Date: 4/15/2015
 * Time: 8:06 PM
 */

//including this file on the bottom of each file so we can easily update the versions if necessary
-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="../js/contact.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="../dist/js/bootstrap.min.js"></script>