            <li class="active"><a href="/">Home</a></li>
            <li><a href="/monitoring">Monitoring</a></li>
            <li><a href="/vintage">Vintage bikes</a></li>
            <li><a href="/musics">Music</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Links<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="https://www.youtube.com/channel/UCY-0sa-YUmVUR_Xm54GBanw">Ethans YouTube Channel</a></li>
                    <!-- <li><a href="#">One more separated link</a></li> -->
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/records">Record collection</a></li>
                    <li><a href="/mileage">Motorcycle mileage</a></li>
                    <!-- <li><a href="#">One more separated link</a></li> -->
                </ul>
            </li>

